# Credit Risk Resampling Techniques

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

# Read the CSV and Perform Basic Data Cleaning

In [3]:
columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [16]:
# Load the data
file_path = Path('/LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1, engine='python')[:-2]
df = df.loc[:, columns].copy()


# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

loan_amnt  int_rate  ...  hardship_flag debt_settlement_flag
0    10500.0    0.1719  ...              N                    N
1    25000.0    0.2000  ...              N                    N
2    20000.0    0.2000  ...              N                    N
3    10000.0    0.1640  ...              N                    N
4    22000.0    0.1474  ...              N                    N

[5 rows x 86 columns]

In [30]:
df['loan_status'].unique()
new_df = df.copy()
new_df['loan_status'] = new_df['loan_status'].map({'low_risk': 0, 'high_risk': 1})

In [29]:
new_df.head()

loan_amnt  int_rate  ...  hardship_flag debt_settlement_flag
0    10500.0    0.1719  ...              N                    N
1    25000.0    0.2000  ...              N                    N
2    20000.0    0.2000  ...              N                    N
3    10000.0    0.1640  ...              N                    N
4    22000.0    0.1474  ...              N                    N

[5 rows x 86 columns]

In [32]:
newer_df = pd.get_dummies(new_df)
newer_df.head()

loan_amnt  int_rate  ...  hardship_flag_N  debt_settlement_flag_N
0    10500.0    0.1719  ...                1                       1
1    25000.0    0.2000  ...                1                       1
2    20000.0    0.2000  ...                1                       1
3    10000.0    0.1640  ...                1                       1
4    22000.0    0.1474  ...                1                       1

[5 rows x 96 columns]

# Split the Data into Training and Testing

In [34]:
# Create our features
X = newer_df.drop(columns= 'loan_status')


# Create our target
y = newer_df['loan_status'].ravel()

In [38]:
X.describe()

loan_amnt      int_rate  ...  hardship_flag_N  debt_settlement_flag_N
count  68817.000000  68817.000000  ...          68817.0                 68817.0
mean   16677.594562      0.127718  ...              1.0                     1.0
std    10277.348590      0.048130  ...              0.0                     0.0
min     1000.000000      0.060000  ...              1.0                     1.0
25%     9000.000000      0.088100  ...              1.0                     1.0
50%    15000.000000      0.118000  ...              1.0                     1.0
75%    24000.000000      0.155700  ...              1.0                     1.0
max    40000.000000      0.308400  ...              1.0                     1.0

[8 rows x 95 columns]

In [39]:
# Check the balance of our target values
np.unique(y, return_counts=True)

(array([0, 1]), array([68470,   347]))

In [84]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
Counter(y_train)

Counter({0: 51366, 1: 246})

# Oversampling

In this section, you will compare two oversampling algorithms to determine which algorithm results in the best performance. You will oversample the data using the naive random oversampling algorithm and the SMOTE algorithm. For each algorithm, be sure to complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

### Naive Random Oversampling

In [58]:
# Resample the training data with the RandomOversampler
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({0: 51366, 1: 51366})

In [59]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [60]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.6579148297196418

In [61]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[10313,  6791],
       [   29,    72]])

In [62]:
# Print the imbalanced classification report (0 means low_risk, and 1 means high_risk)
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.60      0.71      0.75      0.66      0.43     17104
          1       0.01      0.71      0.60      0.02      0.66      0.43       101

avg / total       0.99      0.60      0.71      0.75      0.66      0.43     17205



### SMOTE Oversampling

In [63]:
# Resample the training data with SMOTE
from imblearn.over_sampling import SMOTE
X_resampled_SMOTE, y_resampled_SMOTE = SMOTE(random_state=1,
sampling_strategy='auto').fit_resample(X_train, y_train)
Counter(y_resampled_SMOTE)

Counter({0: 51366, 1: 51366})

In [64]:
# Train the Logistic Regression model using the resampled data
SMOTE_model = LogisticRegression(solver='lbfgs', random_state=1)
SMOTE_model.fit(X_resampled_SMOTE, y_resampled_SMOTE)

LogisticRegression(random_state=1)

In [65]:
# Calculated the balanced accuracy score
y_pred_SMOTE = SMOTE_model.predict(X_test)
balanced_accuracy_score(y_test, y_pred_SMOTE)

0.662861851549982

In [66]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[10313,  6791],
       [   29,    72]])

In [67]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.60      0.71      0.75      0.66      0.43     17104
          1       0.01      0.71      0.60      0.02      0.66      0.43       101

avg / total       0.99      0.60      0.71      0.75      0.66      0.43     17205



# Undersampling

In this section, you will test an undersampling algorithms to determine which algorithm results in the best performance compared to the oversampling algorithms above. You will undersample the data using the Cluster Centroids algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [68]:
# Resample the data using the ClusterCentroids resampler
# Warning: This is a large dataset, and this step may take some time to complete
from imblearn.under_sampling import ClusterCentroids
cc = ClusterCentroids(random_state=1)
X_resampled_cluster, y_resampled_cluster = cc.fit_resample(X_train, y_train)


In [70]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
cluster_model = LogisticRegression(solver='lbfgs', random_state=1)
cluster_model.fit(X_resampled_cluster, y_resampled_cluster)
Counter(y_resampled_cluster)

Counter({0: 246, 1: 246})

In [72]:
# Calculated the balanced accuracy score
y_pred = cluster_model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.5442661782548694

In [73]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[ 6764, 10340],
       [   31,    70]])

In [74]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.40      0.69      0.57      0.52      0.27     17104
          1       0.01      0.69      0.40      0.01      0.52      0.28       101

avg / total       0.99      0.40      0.69      0.56      0.52      0.27     17205



# Combination (Over and Under) Sampling

In this section, you will test a combination over- and under-sampling algorithm to determine if the algorithm results in the best performance compared to the other sampling algorithms above. You will resample the data using the SMOTEENN algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [76]:
# Resample the training data with SMOTEENN
# Warning: This is a large dataset, and this step may take some time to complete
from imblearn.combine import SMOTEENN
smote_enn = SMOTEENN(random_state=0)
X_resampled_SMOTEEN, y_resampled_SMOTEEN = smote_enn.fit_resample(X_train, y_train)

In [79]:
# Train the Logistic Regression model using the resampled data
model_SMOTEEN = LogisticRegression(solver='lbfgs', random_state=1)
model_SMOTEEN.fit(X_resampled_SMOTEEN, y_resampled_SMOTEEN)
Counter(y_resampled_SMOTEEN)

Counter({0: 46660, 1: 51359})

In [80]:
# Calculated the balanced accuracy score
y_pred = model_SMOTEEN.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.6361160379368151

In [81]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[9906, 7198],
       [  31,   70]])

In [83]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.58      0.69      0.73      0.63      0.40     17104
          1       0.01      0.69      0.58      0.02      0.63      0.41       101

avg / total       0.99      0.58      0.69      0.73      0.63      0.40     17205

